#!/bin/sh

case "$1" in
dhcpv4client)
	exec udhcpc -f -t 0 -i "$2" -H "$(hostname)" -x "0x4d:07484f4d454e4554" -s /usr/share/hnetd/dhcp.script
	;;
	
dhcpv6client)
	exec odhcp6c -P0 -F -s /usr/share/hnetd/dhcpv6.script -u HOMENET "$2"
	;;
	
setfilter|unsetfilter)
	[ "$1" = "setfilter" ] && act="-A" || act="-D"
	for cmd in iptables ip6tables; do
		$cmd $act FORWARD -i "$2" -p tcp -m conntrack --ctstate NEW,INVALID -j REJECT --reject-with tcp-reset
		$cmd $act FORWARD -i "$2" -m conntrack --ctstate NEW,INVALID -j REJECT --reject-with icmp-port-unreachable
		$cmd $act INPUT -i "$2" -p tcp -m conntrack --ctstate NEW,INVALID -j REJECT --reject-with tcp-reset
		$cmd $act INPUT -i "$2" -m conntrack --ctstate NEW,INVALID -j REJECT --reject-with icmp-port-unreachable
	done
	;;

newaddr|deladdr)
	[ "$1" = "newaddr" ] && act="replace" || act="del"
	[ -n "$4" -a -n "$5" ] && args="preferred_lft $4 valid_lft $5" || args=""
	ip address $act "$3" dev "$2" $args
	;;

newroute|delroute)
	[ "$1" = "newroute" ] && act="replace" || act="del"
	if [ -n "$6" ]; then
		ip -6 route "$act" "$3" from "$6" via "$4" dev "$2" metric "$5"
	else
		ip route "$act" "$3" via "$4" dev "$2" metric "$5"
	fi
	;;

startdhcp)
	uci batch <<-EOF
	set dhcp.$2=dhcp
	set dhcp.$2.ifname=$2
	set dhcp.$2.dhcpv6=server
	set dhcp.$2.dhcpv4=server
	set dhcp.$2.ra=server
	commit dhcp
EOF
	killall -SIGHUP odhcpd
	;;
	
stopdhcp)
	uci batch <<-EOF
	delete dhcp.$2
	commit dhcp
EOF
	killall -SIGHUP odhcpd
	;;

setdhcpv6)
	[ -z "$DNS" ] && exit 0
	uci batch <<-EOF
	set dhcp.$2=dhcp
	set dhcp.$2.dns=$DNS
	set dhcp.$2.domain=$SEARCH
	commit dhcp
EOF
	killall -SIGHUP odhcpd
	;;

esac
